# lib/urls.py
from django.urls import path
from . import views

from django.views.static import serve
app_name='workersystem'
urlpatterns = [
    path('addadmin/', views.addadmin, name='addadmin'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('do_login/',views.do_login,name='do_login'),
    path('index/',views.index,name='index'),
    path('display/',views.display,name='display'),
    path('workers/',views.workers,name='workers'),
    path('addworker/',views.addworker,name='addworker'),
    path('workersignup/',views.workersignup,name='workersignup'),
    path('getdata/',views.getdata,name='getdata'),
    path('getdata2/',views.getdata2,name='getdata2'),
    path('ruleshaveread/',views.ruleshaveread,name='ruleshaveread'),
    path('rulesunread/',views.rulesunread,name='rulesunread'),
    path('moreworkerinfo/',views.moreworkerinfo,name='moreworkerinfo'),
    path('deleteworker/',views.deleteworker,name='deleteworker'),
    path('deleteworkerlist/',views.deleteworkerlist,name='deleteworkerlist'),
    path('personget/',views.personget,name='personget'),
    path('personruluesdelete/',views.personruluesdelete,name='personruluesdelete'),
    path('rulesunreaddata/',views.rulesunreaddata,name='rulesunreaddata'),
    path('ruleshavareaddata/',views.ruleshavareaddata,name='ruleshavareaddata'),
    path('rulescomfirmread/',views.rulescomfirmread,name='rulescomfirmread'),
    path('deleterulesrecord/',views.deleterulesrecord,name='deleterulesrecord'),
    path('getday/',views.getday,name='getday'),
    path('deleterulesrecordlist/',views.deleterulesrecordlist,name='deleterulesrecordlist'),
    path('getmonth/',views.getmonth,name='getmonth'),
    path('workercounts/',views.workercounts,name='workercounts'),
    path('logout/',views.logout,name='logout'),
    path('getSession/',views.getSession,name='getSession'),
    path('rulescomfirmreadlist/',views.rulescomfirmreadlist,name='rulescomfirmreadlist'),
    path('userinfo/',views.userinfo,name='userinfo'),
    path('usersafe/',views.usersafe,name='usersafe'),
    path('editinfo/',views.editinfo,name='editinfo'),
    path('pwdsafe/',views.pwdsafe,name='pwdsafe'),
    path('changepwd/',views.changepwd,name='changepwd'),
    path('changemail/',views.changemail,name='changemail'),
    path('updateinfo/',views.updateinfo,name='updateinfo'),
    path('getadmin/',views.getadmin,name='getadmin'),
    path('getlv/',views.getlv,name='getlv'),
    path('get_video_time/',views.get_video_time,name='get_video_time'),
    path('get_video_times/',views.get_video_times,name='get_video_times'),
    path('get_user/', views.get_user, name='get_user'),
    path('insert_video/',views.insert_video,name='insert_video'),
]